const weatherImages = {
  0: "../images/sunny.png",
  1: "../images/partly-cloudy.png",
  2: "../images/partly-cloudy.png",
  3: "../images/cloudy.png",
  45: "../images/fog.png",
  48: "../images/fog.png",
  51: "../images/light-rain.png",
  53: "../images/light-rain.png",
  55: "../images/light-rain.png",
  56: "../images/light-rain.png",
  57: "../images/light-rain.png",
  61: "../images/rain.png",
  63: "../images/rain.png",
  65: "../images/rain.png",
  66: "../images/freezing-rain.png",
  67: "../images/freezing-rain.png",
  71: "../images/snowflake.png",
  73: "../images/snowflake.png",
  75: "../images/snowflake.png",
  77: "../images/haile.png",
  80: "../images/shower.png",
  81: "../images/shower.png",
  82: "../images/shower.png",
  85: "../images/shower.png",
  86: "../images/shower.png",
  95: "../images/thunder.png",
  96: "../images/thunder.png",
  99: "../images/thunder.png",
};

export default weatherImages;
